### PR TITLE
build: Bump dependencies

### LINKED ISSUE #77: Yargs version brings a vulnerability
Any plan to update this package to fix the low vulnerability `Prototype Pollution`?

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixes #77.

### CODE REVIEW

**Review by iker-barriocanal — APPROVED** [review]

**Comment by rhcarvalho** [comment]
@iker-barriocanal before we merge this, could you please sanity check that it doesn't break the wizard?

**Review by iker-barriocanal — APPROVED** [review]

**Comment by rhcarvalho** [comment]
@HazAT could you please sanity-check that bumping `xcode` and `xmldom` do not break the wizards for Cordova and ReactNative?

**Comment by HazAT** [comment]
@jennmueng Can you please make one test run with these new deps so we are sure the world is not broken

**Review by jennmueng — APPROVED** [review]
@HazAT Tested on React Native and Cordova apps with rebase off of latest master, install/uninstall. Works perfectly on RN, but some unusual behavior on Cordova still, but not related to this PR. So we're good to go.

**Comment by rhcarvalho** [comment]
Thanks @jennmueng

**Pull request merged**
